POST http://localhost:8800/api/auth/register
Content-Type: application/json

{
    "username": "truong",
    "password": "truong"
}

###

POST http://localhost:8800/api/auth/login
Content-Type: application/json

{
    "username": "kail",
    "password": "kail2411"
}
###

POST http://localhost:8800/api/posts
Content-Type: application/json
Authorization: Kail eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWRkZGQ1MDIwMjY1YzY1Y2ZmYTAiLCJpYXQiOjE2NDc0NDU2NzB9.r_hoK-m8TVXX5GbfecchPehc_vyEUggeyQ0kY3NwS3c

{
    "title": "React2",
    "desc": "React2",
    "url": "React.com2",
    "img": "react2"
}



###

PUT  http://localhost:8800/api/posts/62320f30d3afff5877dc2ba5
Content-Type: application/json
Authorization: Kail eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWRkZGQ1MDIwMjY1YzY1Y2ZmYTAiLCJpYXQiOjE2NDc0NDU2NzB9.r_hoK-m8TVXX5GbfecchPehc_vyEUggeyQ0kY3NwS3c

{
    "title": "Update to post",
    "desc": "Say bye",
    "url": "zing.vn",
    "img": "tr"
}

###

DELETE http://localhost:8800/api/posts/62320f30d3afff5877dc2ba5
Authorization: Kail eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWRkZGQ1MDIwMjY1YzY1Y2ZmYTAiLCJpYXQiOjE2NDc0NDU2NzB9.r_hoK-m8TVXX5GbfecchPehc_vyEUggeyQ0kY3NwS3c


###
POST http://localhost:8800/api/loaitintuc/add
Content-Type: application/json
Authorization: Kail eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWRkZGQ1MDIwMjY1YzY1Y2ZmYTAiLCJpYXQiOjE2NDc0NDU2NzB9.r_hoK-m8TVXX5GbfecchPehc_vyEUggeyQ0kY3NwS3c

{
    "tenloaitintuc": "bóng đá ngoại hạng anh"
}
###

GET http://localhost:8800/api/sans
Authorization: Kail eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWRkZGQ1MDIwMjY1YzY1Y2ZmYTAiLCJpYXQiOjE2NDc0NDY0NTd9.WdQVAxYyJeJDbzmW5zuV4tQibNJ9e0ZkjmgLRhFdJi8

###

POST http://localhost:8800/api/sans/add
Content-Type: application/json

{
    "TenSan": "San G",
    "TinhTrang": "Đang hoạt động",
    "LoaiSan": "623d64cb8ab454fcac95a5fc"
}

###

GET http://localhost:8800/api/loaitintuc
Authorization: Kail eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWRkZGQ1MDIwMjY1YzY1Y2ZmYTAiLCJpYXQiOjE2NDc0NDY0NTd9.WdQVAxYyJeJDbzmW5zuV4tQibNJ9e0ZkjmgLRhFdJi8

GET http://localhost:8800/api/sans
###

GET http://localhost:8800/api/sans/623efb931dd9a3762f4030ec

###

PUT http://localhost:8800/api/sans/update/623d66d00d5cae84e74b1d95
Content-Type: application/json

{
    "TenSan": "San A",
    "TinhTrang": "Đang hoạt động",
    "LoaiSan": "623d64cb8ab454fcac95a5fc"
}

###

DELETE http://localhost:8800/api/sans/delete/623d62f1ab5b1b9bc43b3839

###
GET http://localhost:8800/api/loaisan

###

POST http://localhost:8800/api/loaisan/add
Content-Type: application/json

{
    "tenloaisan": "Sân 5",
    "soluongnguoi": 10,
    "gia": 500000
}
###

POST http://localhost:8800/api/tintuc/add
Content-Type: application/json
Authorization: Kail eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWRkZGQ1MDIwMjY1YzY1Y2ZmYTAiLCJpYXQiOjE2NDc0NDU2NzB9.r_hoK-m8TVXX5GbfecchPehc_vyEUggeyQ0kY3NwS3c

{
    "TieuDe": "React2",
    "NoiDung": "React2",
    "NgayLap": "04/01/2022",
    "LoaiTinTuc": "6246a64d617977a94133b0de",
    "User": "6231edddd5020265c65cffa0"
}

###
DELETE http://localhost:8800/api/tintuc/delete/6247c55a9cd8e25489b206cc
Authorization: Kail eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWRkZGQ1MDIwMjY1YzY1Y2ZmYTAiLCJpYXQiOjE2NDc0NDY0NTd9.WdQVAxYyJeJDbzmW5zuV4tQibNJ9e0ZkjmgLRhFdJi8