POST http://localhost:8800/api/auth/register
Content-Type: application/json

{
    "username": "hiep",
    "password": "hiep3110"
}

###

POST http://localhost:8800/api/auth/login
Content-Type: application/json

{
    "username": "kail",
    "password": "kail2411"
}
###

POST http://localhost:8800/api/posts
Content-Type: application/json
Authorization: Kail eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWRkZGQ1MDIwMjY1YzY1Y2ZmYTAiLCJpYXQiOjE2NDc0NDU2NzB9.r_hoK-m8TVXX5GbfecchPehc_vyEUggeyQ0kY3NwS3c

{
    "title": "my second post",
    "desc": "hello",
    "url": "youtube.com",
    "img": "one"
}

###

GET http://localhost:8800/api/posts
Authorization: Kail eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWRkZGQ1MDIwMjY1YzY1Y2ZmYTAiLCJpYXQiOjE2NDc0NDY0NTd9.WdQVAxYyJeJDbzmW5zuV4tQibNJ9e0ZkjmgLRhFdJi8

###

PUT  http://localhost:8800/api/posts/62320f30d3afff5877dc2ba5
Content-Type: application/json
Authorization: Kail eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWRkZGQ1MDIwMjY1YzY1Y2ZmYTAiLCJpYXQiOjE2NDc0NDU2NzB9.r_hoK-m8TVXX5GbfecchPehc_vyEUggeyQ0kY3NwS3c

{
    "title": "Update to post",
    "desc": "Say bye",
    "url": "zing.vn",
    "img": "tr"
}

###

DELETE http://localhost:8800/api/posts/62320f30d3afff5877dc2ba5
Authorization: Kail eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWRkZGQ1MDIwMjY1YzY1Y2ZmYTAiLCJpYXQiOjE2NDc0NDU2NzB9.r_hoK-m8TVXX5GbfecchPehc_vyEUggeyQ0kY3NwS3c
