POST http://localhost:8800/api/auth/register
Content-Type: application/json

{
    "username": "truong",
    "password": "truong"
}

###

POST http://localhost:8800/api/auth/login
Content-Type: application/json

{
    "username": "kail",
    "password": "kail2411"
}
###

POST http://localhost:8800/api/posts
Content-Type: application/json
Authorization: Kail eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWRkZGQ1MDIwMjY1YzY1Y2ZmYTAiLCJpYXQiOjE2NDc0NDU2NzB9.r_hoK-m8TVXX5GbfecchPehc_vyEUggeyQ0kY3NwS3c

{
    "title": "React2",
    "desc": "React2",
    "url": "React.com2",
    "img": "react2"
}

###

GET http://localhost:8800/api/posts

###

PUT  http://localhost:8800/api/posts/62320f30d3afff5877dc2ba5
Content-Type: application/json
Authorization: Kail eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWRkZGQ1MDIwMjY1YzY1Y2ZmYTAiLCJpYXQiOjE2NDc0NDU2NzB9.r_hoK-m8TVXX5GbfecchPehc_vyEUggeyQ0kY3NwS3c

{
    "title": "Update to post",
    "desc": "Say bye",
    "url": "zing.vn",
    "img": "tr"
}

###

DELETE http://localhost:8800/api/posts/62320f30d3afff5877dc2ba5
Authorization: Kail eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWRkZGQ1MDIwMjY1YzY1Y2ZmYTAiLCJpYXQiOjE2NDc0NDU2NzB9.r_hoK-m8TVXX5GbfecchPehc_vyEUggeyQ0kY3NwS3c

###

GET http://localhost:8800/api/sans
Authorization: Kail eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWRkZGQ1MDIwMjY1YzY1Y2ZmYTAiLCJpYXQiOjE2NDc0NDY0NTd9.WdQVAxYyJeJDbzmW5zuV4tQibNJ9e0ZkjmgLRhFdJi8

###

POST http://localhost:8800/api/sans/add
Content-Type: application/json

{
    "TenSan": "San G",
    "TinhTrang": "Đang hoạt động",
    "LoaiSan": "623d64cb8ab454fcac95a5fc"
}

###

GET http://localhost:8800/api/sans
###

GET http://localhost:8800/api/sans/623f125c93169afa4e4fe71e

###

PUT http://localhost:8800/api/sans/update/623d66d00d5cae84e74b1d95
Content-Type: application/json

{
    "TenSan": "San A",
    "TinhTrang": "Đang hoạt động",
    "LoaiSan": "623d64cb8ab454fcac95a5fc"
}

###

DELETE http://localhost:8800/api/sans/delete/623d62f1ab5b1b9bc43b3839

###
GET http://localhost:8800/api/loaisan

###
GET http://localhost:8800/api/loaisan/623f25bf35fe04520d21bf41

###

POST http://localhost:8800/api/loaisan/add
Content-Type: application/json

{
    "tenloaisan": "Sân 5",
    "soluongnguoi": 10,
    "gia": 500000
}

###
GET http://localhost:8800/api/khunggio

###

POST http://localhost:8800/api/hoadon/add
Content-Type: application/json

{
    "TongTien": 700000
}

###

PUT http://localhost:8800/api/hoadon/update/6245c10d1147ca955ffbf3c3
Content-Type: application/json


###
GET http://localhost:8800/api/hoadon

###

POST http://localhost:8800/api/phieudatsan/add
Content-Type: application/json

{
    "TongTien": 1500,
    "IDHoaDon": "6245c0ce1147ca955ffbf3c1",
    "userID": "6231edddd5020265c65cffa0"
}

###

DELETE http://localhost:8800/api/phieudatsan/delete/6245d012707f932ec247c390

###
GET http://localhost:8800/api/phieudatsan

###

POST http://localhost:8800/api/chitietphieudatsan/add
Content-Type: application/json

{ 
    "IDPhieuDatSan": "6245d68793a321f7bd782c82", 
    "IDSan": "623f125c93169afa4e4fe71e", 
    "NgayDa": "2022-03-31", 
    "ThanhTien": 5000000, 
    "IDKhunggio": "62447040be07951b73251bb2"
}

###
GET http://localhost:8800/api/chitietphieudatsan